### ISSUE TITLE
Question about the architecture

### ISSUE THREAD

**Issue by yadaniyil** [olexale/lego_style_demo#1]
Hey @foxanna  and @olexale. Greetings from Ukraine and nice talk on Flutter Vikings :) So, the questions is - do you have a more complex example of this architecture?
Specifically, I'm interested in 
1) If the project has Firebase, it will be initialized only in the main app module and then, e.g. FirebaseAnalytics will be passed via get_it to the feature module?
2) Is the GetIt instance shared between all the modules? I know that GetIt instances could be scoped, so do you use the scoped get_it instance for some dependencies in the feature?

**Comment by olexale** [comment]
Thank you for reaching out, @yadaniyil! Unfortunately, we are unable to provide more complex examples because this architecture came from proprietary projects that cannot be open-sourced. All teams I worked with had different preferences and slightly different implementations, so consider this repo an example of the approach you can adopt according to your liking. The main idea was to demonstrate that with Flutter it is extremely easy to split the app into many independent pieces, the implementation might significantly vary.
1. I recommend wrapping third parties with utility packages. That will keep them isolated and will not allow them to spread across the codebase. With that, the initialization will stay in the utility package. Now you'll have a problem with initializing it as early as possible, but that's a separate topic.
2. We have a single GetIt instance that is used indirectly as it is wrapped in a utility package too. Each feature creates and operates within its own scope within a shared GetIt instance.

**Comment by olexale** [comment]
@yadaniyil, did I answer your question or there is something you would want to know more about?

**Comment by vietstone-ng** [comment]
@olexale Sorry for bothering you. I have a question about networking, authentication, and token injecting into the request/repository. How do you manage that with this architecture? Thank you.

**Comment by olexale** [comment]
@vietstone-ng, [here](https://medium.com/@foxanna/basic-and-advanced-networking-in-dart-and-flutter-the-tide-way-part-0-introduction-33ac040a4a1c) is a series of articles which describes how we do networking. [Part 3](https://medium.com/@foxanna/basic-and-advanced-networking-in-dart-and-flutter-the-tide-way-d922fb65a01c) describes token injection.
